### PR TITLE
vaapi_encode_av1: Fix build error C2099: initializer is not a constant

### PR DESCRIPTION
**Pull request by sivileri**
When https://github.com/intel-media-ci/ffmpeg/pull/619 lands, we'll have ffmpeg/vaapi support on Windows.

A C2099 build error is found when applying https://github.com/intel-media-ci/cartwheel-ffmpeg/blob/master/patches/0071-lavc-vaapi-support-av1-encode.patch . This patch fixes the build issue by replacing the non constant av_log2(64) with a constant value 6 (2^6 = 64).

Tested the new patch applies correctly by doing:

1. git clone https://github.com/intel/cartwheel-ffmpeg --recursive
2. cd cartwheel-ffmpeg
3. git submodule update --init --recursive
4. cd ffmpeg
5. git am (dir ..\patches*.patch)

cc @xuguangxin @xhaihao @feiwan1 @wenbinc-Bin @galinart @uartie

### CODE REVIEW

**Comment by xhaihao** [comment]
@sivileri  could you please add a Signed-off-by tag ?

**Comment by sivileri** [comment]
> @sivileri could you please add a Signed-off-by tag in commit message ?

@xhaihao Sure, I just pushed a new commit message including it, please let me know if that works.

**Comment by sivileri** [comment]
@xhaihao rebased to resolve conflicts and re-created patch.  Applying all the patches from this branch on top of the master branch of the ffmpeg submodule succeeded. I also set the Signed-off-by message in the commit of this PR. Please let me know what else can I do to move forward with merging this.

**Comment by xhaihao** [comment]
The failures in pre-check were caused by commit fbdba9a1a69fe4df413d9e9df1b11db522946e75.

**Comment by xhaihao** [comment]
LGTM.

**Comment by xhaihao** [comment]
@uartie  @Bin-CI  could you help to merge this patch ? I am not able to merge it due to the failures in pre-check.
